#!/bin/bash

# Get today's date
filename=$(date "+%Y-%m-%d").md
author="Jack Jefferson"

# Check if the file already exists
if [ -f daily/$filename ]; then
  echo "File $filename already exists."
# If not, make the file :)
else
  cat <<EOF > "daily/$filename"
---
title: $filename
author: $author
---
# $filename

## Coding Sessions

### Morning



### Evening


EOF
fi

# Open my preferred editor with the file name.
hx -w daily daily/$filename
